trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TEST_ENV: 'stage'

steps:

- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: Install Node.js

- script: npm install
  displayName: Install Dependencies

- script: |
    npx playwright install --with-deps
  displayName: Install Playwright Browsers

- script: |
    npx playwright test --config=playwright.service.config.js --workers=9
  displayName: Run Playwright Tests

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: playwright-report
    artifact: playwright-report
  condition: always()
  displayName: Publish Playwright Report